# Generated by Django 4.0.4 on 2022-05-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='expanse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'member')], default=2),
        ),
    ]
